name: Deploy Images to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and Push Image'
        run: |
          docker build . --tag ghcr.io/${{github.actor}}/diabetes-pred-api:latest
          docker push ghcr.io/${{github.actor}}/diabetes-pred-api:latest
